import { TarotCard, TarotSuit, Spread, SpreadType } from '../types';
import { Sparkles, Layers, Heart, Briefcase, Grid3x3 } from 'lucide-react';

// 22张大阿卡纳牌
export const MAJOR_ARCANA: TarotCard[] = [
  {
    id: 'major-0',
    name: 'The Fool',
    nameCn: '愚者',
    suit: TarotSuit.MajorArcana,
    number: 0,
    keywords: ['new beginnings', 'innocence', 'adventure', 'freedom'],
    keywordsCn: ['新开始', '天真', '冒险', '自由'],
    upright: '新的开始、纯真的信念、自由的灵魂、勇敢的冒险',
    reversed: '鲁莽冲动、缺乏计划、愚昧无知、错失机会',
    whisper: '勇敢踏出第一步',
    image: '/images/tarot/major-0.png',
  },
  {
    id: 'major-1',
    name: 'The Magician',
    nameCn: '魔术师',
    suit: TarotSuit.MajorArcana,
    number: 1,
    keywords: ['manifestation', 'power', 'skill', 'action'],
    keywordsCn: ['显化', '力量', '技巧', '行动'],
    upright: '创造力、技能、意志力、开始行动',
    reversed: '操纵他人、缺乏才能、延迟行动、浪费潜力',
    whisper: '意念成真的时刻',
  },
  {
    id: 'major-2',
    name: 'The High Priestess',
    nameCn: '女祭司',
    suit: TarotSuit.MajorArcana,
    number: 2,
    keywords: ['intuition', 'mystery', 'subconscious', 'wisdom'],
    keywordsCn: ['直觉', '神秘', '潜意识', '智慧'],
    upright: '直觉、内在知识、神秘智慧、倾听内心',
    reversed: '忽视直觉、表面知识、隐藏信息、缺乏洞察',
    whisper: '倾听你的直觉',
  },
  {
    id: 'major-3',
    name: 'The Empress',
    nameCn: '皇后',
    suit: TarotSuit.MajorArcana,
    number: 3,
    keywords: ['abundance', 'nurturing', 'fertility', 'nature'],
    keywordsCn: ['丰盛', '养育', '生育', '自然'],
    upright: '丰盛、养育、美好生活、自然和谐',
    reversed: '依赖他人、窒息的爱、创造力受阻、物质损失',
    whisper: '丰盛正在到来',
  },
  {
    id: 'major-4',
    name: 'The Emperor',
    nameCn: '皇帝',
    suit: TarotSuit.MajorArcana,
    number: 4,
    keywords: ['authority', 'structure', 'control', 'leadership'],
    keywordsCn: ['权威', '结构', '控制', '领导力'],
    upright: '权威、建立秩序、领导力、父亲形象',
    reversed: '专制独裁、僵化思维、失去控制、缺乏纪律',
    whisper: '秩序源于内心',
  },
  {
    id: 'major-5',
    name: 'The Hierophant',
    nameCn: '教皇',
    suit: TarotSuit.MajorArcana,
    number: 5,
    keywords: ['tradition', 'conformity', 'education', 'belief'],
    keywordsCn: ['传统', '遵从', '教育', '信仰'],
    upright: '传统、精神导师、遵循规则、寻求知识',
    reversed: '反叛、挑战传统、自由思想、新方法',
    whisper: '智慧藏于传承',
  },
  {
    id: 'major-6',
    name: 'The Lovers',
    nameCn: '恋人',
    suit: TarotSuit.MajorArcana,
    number: 6,
    keywords: ['love', 'harmony', 'choice', 'relationships'],
    keywordsCn: ['爱情', '和谐', '选择', '关系'],
    upright: '爱情、和谐关系、价值选择、灵魂伴侣',
    reversed: '关系失衡、价值冲突、错误选择、缺乏和谐',
    whisper: '选择你的心之所向',
  },
  {
    id: 'major-7',
    name: 'The Chariot',
    nameCn: '战车',
    suit: TarotSuit.MajorArcana,
    number: 7,
    keywords: ['willpower', 'victory', 'determination', 'control'],
    keywordsCn: ['意志力', '胜利', '决心', '控制'],
    upright: '意志力、胜利、决心、自我控制',
    reversed: '失去方向、缺乏控制、侵略性、失败',
    whisper: '胜利属于坚定者',
  },
  {
    id: 'major-8',
    name: 'Strength',
    nameCn: '力量',
    suit: TarotSuit.MajorArcana,
    number: 8,
    keywords: ['courage', 'patience', 'compassion', 'influence'],
    keywordsCn: ['勇气', '耐心', '同情', '影响力'],
    upright: '内在力量、勇气、耐心、温柔控制',
    reversed: '自我怀疑、软弱、缺乏信心、暴力倾向',
    whisper: '温柔即是力量',
  },
  {
    id: 'major-9',
    name: 'The Hermit',
    nameCn: '隐士',
    suit: TarotSuit.MajorArcana,
    number: 9,
    keywords: ['introspection', 'solitude', 'wisdom', 'guidance'],
    keywordsCn: ['内省', '独处', '智慧', '指引'],
    upright: '内省、独处、寻找真理、内在指引',
    reversed: '孤立、孤独、过度内向、拒绝建议',
    whisper: '答案在内心深处',
  },
  {
    id: 'major-10',
    name: 'Wheel of Fortune',
    nameCn: '命运之轮',
    suit: TarotSuit.MajorArcana,
    number: 10,
    keywords: ['destiny', 'change', 'cycles', 'karma'],
    keywordsCn: ['命运', '变化', '循环', '因果'],
    upright: '好运、生命周期、转折点、命运安排',
    reversed: '坏运气、失控、抗拒变化、破坏循环',
    whisper: '命运之轮转动',
  },
  {
    id: 'major-11',
    name: 'Justice',
    nameCn: '正义',
    suit: TarotSuit.MajorArcana,
    number: 11,
    keywords: ['fairness', 'truth', 'law', 'balance'],
    keywordsCn: ['公平', '真相', '法律', '平衡'],
    upright: '公正、真相、法律、因果报应',
    reversed: '不公、谎言、逃避责任、偏见',
    whisper: '真相终将显现',
  },
  {
    id: 'major-12',
    name: 'The Hanged Man',
    nameCn: '倒吊人',
    suit: TarotSuit.MajorArcana,
    number: 12,
    keywords: ['sacrifice', 'perspective', 'surrender', 'waiting'],
    keywordsCn: ['牺牲', '视角', '臣服', '等待'],
    upright: '换位思考、暂停、放手、牺牲奉献',
    reversed: '无意义牺牲、停滞不前、抗拒、拖延',
    whisper: '换个角度看世界',
  },
  {
    id: 'major-13',
    name: 'Death',
    nameCn: '死神',
    suit: TarotSuit.MajorArcana,
    number: 13,
    keywords: ['transformation', 'endings', 'change', 'transition'],
    keywordsCn: ['转变', '结束', '改变', '过渡'],
    upright: '转变、结束、新生、放下过去',
    reversed: '抗拒改变、恐惧、停滞、无法放手',
    whisper: '结束即是新生',
  },
  {
    id: 'major-14',
    name: 'Temperance',
    nameCn: '节制',
    suit: TarotSuit.MajorArcana,
    number: 14,
    keywords: ['balance', 'moderation', 'patience', 'harmony'],
    keywordsCn: ['平衡', '节制', '耐心', '和谐'],
    upright: '平衡、节制、耐心、中庸之道',
    reversed: '失衡、过度、缺乏耐心、极端',
    whisper: '中庸之道最智慧',
  },
  {
    id: 'major-15',
    name: 'The Devil',
    nameCn: '恶魔',
    suit: TarotSuit.MajorArcana,
    number: 15,
    keywords: ['bondage', 'addiction', 'materialism', 'temptation'],
    keywordsCn: ['束缚', '上瘾', '物欲', '诱惑'],
    upright: '束缚、成瘾、物质主义、诱惑陷阱',
    reversed: '解脱、觉醒、摆脱束缚、克服诱惑',
    whisper: '挣脱你的枷锁',
  },
  {
    id: 'major-16',
    name: 'The Tower',
    nameCn: '高塔',
    suit: TarotSuit.MajorArcana,
    number: 16,
    keywords: ['upheaval', 'chaos', 'revelation', 'awakening'],
    keywordsCn: ['剧变', '混乱', '启示', '觉醒'],
    upright: '突然改变、混乱、启示、打破幻象',
    reversed: '避免灾难、恐惧改变、延迟必然、个人转变',
    whisper: '破旧方能立新',
  },
  {
    id: 'major-17',
    name: 'The Star',
    nameCn: '星星',
    suit: TarotSuit.MajorArcana,
    number: 17,
    keywords: ['hope', 'inspiration', 'renewal', 'serenity'],
    keywordsCn: ['希望', '灵感', '更新', '宁静'],
    upright: '希望、灵感、宁静、精神引导',
    reversed: '绝望、缺乏信念、气馁、失去方向',
    whisper: '希望永不熄灭',
  },
  {
    id: 'major-18',
    name: 'The Moon',
    nameCn: '月亮',
    suit: TarotSuit.MajorArcana,
    number: 18,
    keywords: ['illusion', 'intuition', 'dreams', 'subconscious'],
    keywordsCn: ['幻象', '直觉', '梦境', '潜意识'],
    upright: '幻觉、直觉、梦境、潜意识恐惧',
    reversed: '释放恐惧、克服焦虑、找到清晰、真相显现',
    whisper: '穿透迷雾见真相',
  },
  {
    id: 'major-19',
    name: 'The Sun',
    nameCn: '太阳',
    suit: TarotSuit.MajorArcana,
    number: 19,
    keywords: ['joy', 'success', 'celebration', 'vitality'],
    keywordsCn: ['喜悦', '成功', '庆祝', '活力'],
    upright: '快乐、成功、庆祝、积极能量',
    reversed: '沮丧、暂时失落、过度乐观、延迟喜悦',
    whisper: '阳光终会照耀',
  },
  {
    id: 'major-20',
    name: 'Judgement',
    nameCn: '审判',
    suit: TarotSuit.MajorArcana,
    number: 20,
    keywords: ['reflection', 'reckoning', 'rebirth', 'awakening'],
    keywordsCn: ['反思', '清算', '重生', '觉醒'],
    upright: '反思、审判、重生、内在呼唤',
    reversed: '自我怀疑、内疚、拒绝改变、逃避责任',
    whisper: '重生的号角响起',
  },
  {
    id: 'major-21',
    name: 'The World',
    nameCn: '世界',
    suit: TarotSuit.MajorArcana,
    number: 21,
    keywords: ['completion', 'achievement', 'travel', 'success'],
    keywordsCn: ['完成', '成就', '旅行', '成功'],
    upright: '完成、成就、圆满、世界之旅',
    reversed: '未完成、寻求终结、缺乏完整、延迟成功',
    whisper: '圆满就在眼前',
  },
];

// 牌阵配置
export const SPREADS: Spread[] = [
  {
    id: SpreadType.Single,
    name: 'Single Card',
    nameCn: '单张抽牌',
    description: 'Quick insight for daily guidance',
    descriptionCn: '每日指引，快速洞察',
    icon: Sparkles,
    positions: [
      {
        index: 0,
        name: 'Guidance',
        nameCn: '指引',
        meaning: 'What you need to know today',
        meaningCn: '今日你需要知道的',
      },
    ],
  },
  {
    id: SpreadType.ThreeCard,
    name: 'Three Card Spread',
    nameCn: '三张牌阵',
    description: 'Past, Present, Future or Situation, Action, Outcome',
    descriptionCn: '过去-现在-未来 或 情况-行动-结果',
    icon: Layers,
    positions: [
      {
        index: 0,
        name: 'Past/Situation',
        nameCn: '过去/情况',
        meaning: 'What brought you here or current situation',
        meaningCn: '是什么带你来到这里，或当前的情况',
      },
      {
        index: 1,
        name: 'Present/Action',
        nameCn: '现在/行动',
        meaning: 'Current energies or action to take',
        meaningCn: '当前的能量或需要采取的行动',
      },
      {
        index: 2,
        name: 'Future/Outcome',
        nameCn: '未来/结果',
        meaning: 'Where things are heading or potential outcome',
        meaningCn: '事情的走向或潜在结果',
      },
    ],
  },
  {
    id: SpreadType.Relationship,
    name: 'Relationship Spread',
    nameCn: '关系牌阵',
    description: 'Insights into your relationship dynamics',
    descriptionCn: '深入了解你的关系动态',
    icon: Heart,
    positions: [
      {
        index: 0,
        name: 'You',
        nameCn: '你',
        meaning: 'Your position and feelings',
        meaningCn: '你的立场和感受',
      },
      {
        index: 1,
        name: 'Partner',
        nameCn: '对方',
        meaning: 'Their position and feelings',
        meaningCn: '对方的立场和感受',
      },
      {
        index: 2,
        name: 'Connection',
        nameCn: '连接',
        meaning: 'The energy between you',
        meaningCn: '你们之间的能量',
      },
      {
        index: 3,
        name: 'Challenge',
        nameCn: '挑战',
        meaning: 'What needs attention',
        meaningCn: '需要注意的地方',
      },
      {
        index: 4,
        name: 'Guidance',
        nameCn: '指引',
        meaning: 'Advice for the relationship',
        meaningCn: '关系的建议',
      },
    ],
  },
  {
    id: SpreadType.Career,
    name: 'Career Spread',
    nameCn: '事业牌阵',
    description: 'Guidance for your professional path',
    descriptionCn: '职业道路的指引',
    icon: Briefcase,
    positions: [
      {
        index: 0,
        name: 'Current Situation',
        nameCn: '当前状况',
        meaning: 'Where you are now professionally',
        meaningCn: '你目前的职业状况',
      },
      {
        index: 1,
        name: 'Challenges',
        nameCn: '挑战',
        meaning: 'Obstacles in your path',
        meaningCn: '你道路上的障碍',
      },
      {
        index: 2,
        name: 'Strengths',
        nameCn: '优势',
        meaning: 'Your professional advantages',
        meaningCn: '你的职业优势',
      },
      {
        index: 3,
        name: 'Opportunities',
        nameCn: '机会',
        meaning: 'Potential paths forward',
        meaningCn: '潜在的前进方向',
      },
      {
        index: 4,
        name: 'Advice',
        nameCn: '建议',
        meaning: 'Guidance for career success',
        meaningCn: '职业成功的指引',
      },
    ],
  },
  {
    id: SpreadType.CelticCross,
    name: 'Celtic Cross',
    nameCn: '凯尔特十字',
    description: 'Comprehensive 10-card reading for deep insight',
    descriptionCn: '全面的10张牌深度解读',
    icon: Grid3x3,
    positions: [
      {
        index: 0,
        name: 'Present',
        nameCn: '现在',
        meaning: 'Current situation',
        meaningCn: '当前情况',
      },
      {
        index: 1,
        name: 'Challenge',
        nameCn: '挑战',
        meaning: 'What crosses you',
        meaningCn: '你面临的挑战',
      },
      {
        index: 2,
        name: 'Foundation',
        nameCn: '根基',
        meaning: 'Basis of the situation',
        meaningCn: '情况的基础',
      },
      {
        index: 3,
        name: 'Past',
        nameCn: '过去',
        meaning: 'Recent past influences',
        meaningCn: '近期过去的影响',
      },
      {
        index: 4,
        name: 'Crown',
        nameCn: '顶端',
        meaning: 'Best outcome',
        meaningCn: '最好的结果',
      },
      {
        index: 5,
        name: 'Future',
        nameCn: '未来',
        meaning: 'Near future',
        meaningCn: '近期未来',
      },
      {
        index: 6,
        name: 'Your Attitude',
        nameCn: '你的态度',
        meaning: 'How you see yourself',
        meaningCn: '你如何看待自己',
      },
      {
        index: 7,
        name: 'External',
        nameCn: '外部',
        meaning: 'External influences',
        meaningCn: '外部影响',
      },
      {
        index: 8,
        name: 'Hopes/Fears',
        nameCn: '希望/恐惧',
        meaning: 'Your hopes and fears',
        meaningCn: '你的希望和恐惧',
      },
      {
        index: 9,
        name: 'Outcome',
        nameCn: '结果',
        meaning: 'Final outcome',
        meaningCn: '最终结果',
      },
    ],
  },
];

// 所有塔罗牌（目前仅使用大阿卡纳）
export const ALL_TAROT_CARDS: TarotCard[] = [...MAJOR_ARCANA];

// 随机抽牌
export function drawCards(count: number): TarotCard[] {
  const shuffled = [...ALL_TAROT_CARDS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

// 判断是否逆位（30%概率）
export function isCardReversed(): boolean {
  return Math.random() < 0.3;
}

